### ISSUE TITLE
More hic files

### ISSUE THREAD

**Issue by ardy20** [WarrenLab/hic-scaffolding-nf#1]
Hello
Thanks for creating this pipeline. I am trying to use it in our HPC cluster but I have a few questions. 

How to change the script if we have more hic data (let's say 4 or more)? 
For -profile conda option, should we use it once (to install tools) or every time we run the pipeline?
What should be the queue's name in .config file? Do I need to obtain it from our system admin?
Regards

**Comment by ardy20** [comment]
Hello Again

It looks that workflow stopped working with the following messages.

I run the script as: 

nextflow run WarrenLab/hic-scaffolding-nf -profile conda --juicer-tools-jar /scratch/project/hic-scaffolding-nf/juicer_tools_1.22.01.jar --contigs OAust.hic.primary_ctg.fa --r1Reads o.austral.01.fastq --r2Reads o.austral.02.fastq

N E X T F L O W  ~  version 22.10.1
Pulling WarrenLab/hic-scaffolding-nf ...
 downloaded from https://github.com/WarrenLab/hic-scaffolding-nf.git
Launching `https://github.com/WarrenLab/hic-scaffolding-nf` [distraught_goldberg] DSL2 - revision: 2a562a38da [main]

[-        ] process > PRINT_VERSIONS -
executor >  local (4)
[-        ] process > PRINT_VERSIONS -
executor >  local (4)
[6a/6748c5] process > PRINT_VERSIONS     [100%] 1 of 1 ✔
[10/f22e9f] process > SAMTOOLS_FAIDX (1) [100%] 1 of 1 ✔
[c9/a70b7a] process > CHROMAP_INDEX (1)  [100%] 1 of 1 ✔
[97/097af0] process > CHROMAP_ALIGN (1)  [  0%] 0 of 1
[-        ] process > YAHS_SCAFFOLD      -
[-        ] process > JUICER_PRE         -
[-        ] process > ASSEMBLY_STATS     -

**Comment by esrice** [comment]
> How to change the script if we have more hic data (let's say 4 or more)?

The simplest way to do this is probably to cat all the r1s and r2s together respectively.

> For -profile conda option, should we use it once (to install tools) or every time we run the pipeline?

Every time, so that it loads the conda env it created the first time.

> What should be the queue's name in .config file? Do I need to obtain it from our system admin?

This depends on what batch system you are using, if any. See nextflow docs and talk to your system admin, yes

**Comment by esrice** [comment]
> Hello Again
> 
> It looks that workflow stopped working with the following messages.
> 
> I run the script as:
> 
> nextflow run WarrenLab/hic-scaffolding-nf -profile conda --juicer-tools-jar /scratch/project/hic-scaffolding-nf/juicer_tools_1.22.01.jar --contigs OAust.hic.primary_ctg.fa --r1Reads o.austral.01.fastq --r2Reads o.austral.02.fastq
> 
> N E X T F L O W ~ version 22.10.1 Pulling WarrenLab/hic-scaffolding-nf ... downloaded from https://github.com/WarrenLab/hic-scaffolding-nf.git Launching `https://github.com/WarrenLab/hic-scaffolding-nf` [distraught_goldberg] DSL2 - revision: [2a562a3](https://github.com/WarrenLab/hic-scaffolding-nf/commit/2a562a38da00a3337fdc08bfc569ca14242fd2c6) [main]
> 
> [- ] process > PRINT_VERSIONS - executor > local (4) [- ] process > PRINT_VERSIONS - executor > local (4) [6a/6748c5] process > PRINT_VERSIONS [100%] 1 of 1 ✔ [10/f22e9f] process > SAMTOOLS_FAIDX (1) [100%] 1 of 1 ✔ [c9/a70b7a] process > CHROMAP_INDEX (1) [100%] 1 of 1 ✔ [97/097af0] process > CHROMAP_ALIGN (1) [ 0%] 0 of 1 [- ] process > YAHS_SCAFFOLD - [- ] process > JUICER_PRE - [- ] process > ASSEMBLY_STATS -

I don't see any error message here; either this is still running just fine or you didn't copy the full output.

**Comment by ardy20** [comment]
Hello
Thanks. The pipeline worked perfectly. I am checking the results now,
