### ISSUE TITLE
add a way to specify the restriction enzyme in yaHS with -e

### ISSUE THREAD

**Issue by uqunakan** [WarrenLab/hic-scaffolding-nf#2]
Hi, could you please let me know what's the default restriction enzyme used for YaHS tool in this pipeline? Because when we manually run YaHS, we can change it with the -e option. We should be able to specify the restriction enzyme(s) used by the Hi-C experiment (GATC,GANTC etc). In my case GATC is the restriction enzyme used in our HiC experiment. 

Do we need to change nf main file? If so, how to change it and locally run it?

**Comment by esrice** [comment]
I haven't added a way to specify a -e option to yahs. I'll put it on my to-do list, should be pretty quick. In the meantime, you can copy the main.nf script to the directory where you want to run it and then edit the yahs command manually.

**Comment by uqunakan** [comment]
Thank you very much for your response, Edward. I will try to do it.

Thanks and regards,

Ms Upuli Nakandala | PhD student
Robert Henry’s Lab
Queensland Alliance for Agriculture & Food Innovation
Level 6 Hartley Teakle Building [609]
The university of Queensland, St Lucia QLD 4072
Email: ***@***.******@***.***>
Mobile: +61480385195
Website: www.qaafi.uq.edu.au<http://www.qaafi.uq.edu.au>

**Comment by esrice** [comment]
Alright, I added with the latest commit a way to specify addition arguments to yahs. Try

```bash
nextflow WarrenLab/hic-scaffolding-nf -latest -r 6faa2fc [your arguments] --extra-yahs-args "-e GATC"
```

(the `-latest -r 6faa2fc` part is to make sure it uses the most recent version of the pipeline)

**Comment by uqunakan** [comment]
Hi Edward,
I edited the yahs command with -e GATC option in the main.nf script which I have previously installed. Since the command is there now in the main.nf script, I suppose I don’t need to add it to the following command (red colour) which I use to run this script. Am I correct?

nextflow run WarrenLab/hic-scaffolding-nf -profile conda --juicer-tools-jar /scratch/project/qaafi-cnafs/hic-scaffolding-nf/juicer_tools_1.22.01.jar --contigs C.australasica_Rainbow.asm.hic.p_ctg.fa --r1Reads combined_R1.fastq --r2Reads combined_R2.fastq            -e GATC

Thanks and regards,

Ms Upuli Nakandala | PhD student
Robert Henry’s Lab
Queensland Alliance for Agriculture & Food Innovation
Level 6 Hartley Teakle Building [609]
The university of Queensland, St Lucia QLD 4072
Email: ***@***.******@***.***>
Mobile: +61480385195
Website: www.qaafi.uq.edu.au<http://www.qaafi.uq.edu.au>

**Comment by esrice** [comment]
You can either use the most recent version on github (by adding the `-latest -r 6faa2fc` arguments) plus the `--extra-yahs-args "-e GATC"` arguments, or you can run the command the way you originally did with the edited main.nf.

**Comment by uqunakan** [comment]
Hi Edward. Thank you very much. I also need to know whether this pipeline performs any Arima mapping to do 5’ filtering of chimeric reads and to remove PCR duplication of HiC reads. In the main.nf script, I found nothing related to Arima mapping. So, I suppose it only aligns HiC reads to the contig.fa file and the resulting output BAM file is scaffolded with YaHS tool. Is it correct?

Thanks and regards,

Ms Upuli Nakandala | PhD student
Robert Henry’s Lab
Queensland Alliance for Agriculture & Food Innovation
Level 6 Hartley Teakle Building [609]
The university of Queensland, St Lucia QLD 4072
Email: ***@***.******@***.***>
Mobile: +61480385195
Website: www.qaafi.uq.edu.au<http://www.qaafi.uq.edu.au>

**Comment by esrice** [comment]
This pipeline uses chromap for alignment and postprocessing (dealing with pairs, chimeras, duplicates etc.) rather than arima. You can take a look at the documentation of both of these for more information on how the approaches differ.

**Comment by uqunakan** [comment]
Thank you very much Edward.

Best regards,

Ms Upuli Nakandala | PhD student
Robert Henry’s Lab
Queensland Alliance for Agriculture & Food Innovation
Level 6 Hartley Teakle Building [609]
The university of Queensland, St Lucia QLD 4072
Email: ***@***.******@***.***>
Mobile: +61480385195
Website: www.qaafi.uq.edu.au<http://www.qaafi.uq.edu.au>
