### ISSUE TITLE
error on Juicer pre and juicer-tools

### ISSUE THREAD

**Issue by dbajpp0** [WarrenLab/hic-scaffolding-nf#3]
Dear colleague,

I get an error in the pipeline during Juicer pre and perhaps related to juicer tools. I use conda in an ubuntu 22.04

This is the input 
(hic-scaffolding) jpons@tesla:~/Downloads/hic-scaffolding-nf$ nextflow run WarrenLab/hic-scaffolding-nf     --contigs /home/jpons/Downloads/tethys.hifiasm.purgedup.eukaryomly.fasta     --r1Reads /grass/jpp/testhysbaena_genome_PACBIOreads/Tscabra_allHiC_1.fastq.gz     --r2Reads /grass/jpp/testhysbaena_genome_PACBIOreads/Tscabra_allHiC_2.fastq.gz     --juicer-tools-jar /home/jpons/Downloads/juicer_tools.2.04.06.jar --profile conda

and this is the error
N E X T F L O W  ~  version 23.04.3
Launching `https://github.com/WarrenLab/hic-scaffolding-nf` [crazy_heyrovsky] DSL2 - revision: 182d56aaaf [main]
executor >  local (7)
[5a/614463] process > PRINT_VERSIONS     [100%] 1 of 1 ✔
[71/ffd6e6] process > SAMTOOLS_FAIDX (1) [100%] 1 of 1 ✔
[c9/91fb8f] process > CHROMAP_INDEX (1)  [100%] 1 of 1 ✔
[7d/f21320] process > CHROMAP_ALIGN (1)  [100%] 1 of 1 ✔
[47/4117c4] process > YAHS_SCAFFOLD (1)  [100%] 1 of 1 ✔
[22/aaeb5c] process > JUICER_PRE (1)     [  0%] 0 of 1
[9e/1d7d52] process > ASSEMBLY_STATS (1) [100%] 1 of 1 ✔
ERROR ~ Error executing process > 'JUICER_PRE (1)'

Caused by:
  Process `JUICER_PRE (1)` terminated with an error exit status (56)

Command executed:

  juicer pre -a -o out_JBAT         yahs.out.bin         yahs.out_scaffolds_final.agp         contigs.fa.fai
  
  asm_size=$(awk '{s+=$2} END{print s}' contigs.fa.fai)
  java -Xmx36G -jar /home/jpons/Downloads/juicer_tools.2.04.06.jar         pre out_JBAT.txt out_JBAT.hic <(echo "assembly ${asm_size}")

Command exit status:
  56

Command output:
  WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
  WARN [2023-09-28T15:50:49,046]  [Globals.java:138] [main]  Development mode is enabled
  Using 1 CPU thread(s)
  Not including fragment map
  Start preprocess
  Writing header
  Writing body
  ..
  Writing footer
  nBytesV5: 7492146
  masterIndexPosition: 430962352
  
  Finished preprocess

Command error:
  [I::main_pre] make juicer pre input from BIN file yahs.out.bin
  [I::make_juicer_pre_file_from_bin] 52982560 read pairs processed
  [I::main_pre] genome size: 1359782678
  [I::main_pre] scale factor: 1
  [I::main_pre] chromosome sizes for juicer_tools pre -
  PRE_C_SIZE: assembly 1359782678
  [I::main_pre] JUICER_PRE CMD: java -Xmx36G -jar ${juicer_tools} pre out_JBAT.txt out_JBAT.hic <(echo "assembly 1359782678")
  [I::main_pre] Version: 1.1
  [I::main_pre] CMD: juicer pre -a -o out_JBAT yahs.out.bin yahs.out_scaffolds_final.agp contigs.fa.fai
  [I::main_pre] Real time: 18.290 sec; CPU: 18.239 sec; Peak RSS: 0.003 GB
  WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
  WARN [2023-09-28T15:50:49,046]  [Globals.java:138] [main]  Development mode is enabled
  Using 1 CPU thread(s)
  Not including fragment map
  Start preprocess
  Writing header
  Writing body
  ..
  Writing footer
  nBytesV5: 7492146
  masterIndexPosition: 430962352
  
  Finished preprocess
  0 0
  java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
  	at juicebox.tools.utils.norm.final2.FinalScale.scaleToTargetVector(FinalScale.java:150)
  	at juicebox.tools.utils.norm.ZeroScale.scale(ZeroScale.java:36)
  	at juicebox.tools.utils.norm.ZeroScale.mmbaScaleToVector(ZeroScale.java:executor >  local (7)
[5a/614463] process > PRINT_VERSIONS     [100%] 1 of 1 ✔
[71/ffd6e6] process > SAMTOOLS_FAIDX (1) [100%] 1 of 1 ✔
[c9/91fb8f] process > CHROMAP_INDEX (1)  [100%] 1 of 1 ✔
[7d/f21320] process > CHROMAP_ALIGN (1)  [100%] 1 of 1 ✔
[47/4117c4] process > YAHS_SCAFFOLD (1)  [100%] 1 of 1 ✔
[22/aaeb5c] process > JUICER_PRE (1)     [100%] 1 of 1, failed: 1 ✘
[9e/1d7d52] process > ASSEMBLY_STATS (1) [100%] 1 of 1 ✔
ERROR ~ Error executing process > 'JUICER_PRE (1)'

Caused by:
  Process `JUICER_PRE (1)` terminated with an error exit status (56)

Command executed:

  juicer pre -a -o out_JBAT         yahs.out.bin         yahs.out_scaffolds_final.agp         contigs.fa.fai
  
  asm_size=$(awk '{s+=$2} END{print s}' contigs.fa.fai)
  java -Xmx36G -jar /home/jpons/Downloads/juicer_tools.2.04.06.jar         pre out_JBAT.txt out_JBAT.hic <(echo "assembly ${asm_size}")

Command exit status:
  56

Command output:
  WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
  WARN [2023-09-28T15:50:49,046]  [Globals.java:138] [main]  Development mode is enabled
  Using 1 CPU thread(s)
  Not including fragment map
  Start preprocess
  Writing header
  Writing body
  ..
  Writing footer
  nBytesV5: 7492146
  masterIndexPosition: 430962352
  
  Finished preprocess

Command error:
  [I::main_pre] make juicer pre input from BIN file yahs.out.bin
  [I::make_juicer_pre_file_from_bin] 52982560 read pairs processed
  [I::main_pre] genome size: 1359782678
  [I::main_pre] scale factor: 1
  [I::main_pre] chromosome sizes for juicer_tools pre -
  PRE_C_SIZE: assembly 1359782678
  [I::main_pre] JUICER_PRE CMD: java -Xmx36G -jar ${juicer_tools} pre out_JBAT.txt out_JBAT.hic <(echo "assembly 1359782678")
  [I::main_pre] Version: 1.1
  [I::main_pre] CMD: juicer pre -a -o out_JBAT yahs.out.bin yahs.out_scaffolds_final.agp contigs.fa.fai
  [I::main_pre] Real time: 18.290 sec; CPU: 18.239 sec; Peak RSS: 0.003 GB
  WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
  WARN [2023-09-28T15:50:49,046]  [Globals.java:138] [main]  Development mode is enabled
  Using 1 CPU thread(s)
  Not including fragment map
  Start preprocess
  Writing header
  Writing body
  ..
  Writing footer
  nBytesV5: 7492146
  masterIndexPosition: 430962352
  
  Finished preprocess
  0 0
  java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
  	at juicebox.tools.utils.norm.final2.FinalScale.scaleToTargetVector(FinalScale.java:150)
  	at juicebox.tools.utils.norm.ZeroScale.scale(ZeroScale.java:36)
  	at juicebox.tools.utils.norm.ZeroScale.mmbaScaleToVector(ZeroScale.java:86)
  	at juicebox.tools.utils.norm.NormalizationCalculations.computeMMBA(NormalizationCalculations.java:566)
  	at juicebox.tools.utils.norm.NormalizationCalculations.getNorm(NormalizationCalculations.java:343)
  	at juicebox.tools.utils.norm.GenomeWideNormalizationVectorUpdater.getWGVectors(GenomeWideNormalizationVectorUpdater.java:163)
  	at juicebox.tools.utils.norm.GenomeWideNormalizationVectorUpdater.updateHicFileForGWfromPreAddNormOnly(GenomeWideNormalizationVectorUpdater.java:127)
  	at juicebox.tools.utils.norm.NormalizationVectorUpdater.updateHicFile(NormalizationVectorUpdater.java:105)
  	at juicebox.tools.clt.old.PreProcessing.run(PreProcessing.java:153)
  	at juicebox.tools.HiCTools.main(HiCTools.java:94)

Work dir:
  /home/jpons/Downloads/hic-scaffolding-nf/work/22/aaeb5c1f1b831c0337c163104de1e7

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

 -- Check '.nextflow.log' file for details

I get the same error in despite of using different java or juicer-tools versions.

Thanks in advance,
Joan Pons

**Comment by esrice** [comment]
Have you looked at the input files for this process by going into the workdir as nextflow suggests? The lines
```
0 0
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
```
make me suspect there is an empty input file to this step. The failed step is just for making a heatmap for viewing in juicebox, so the actual scaffolding parts should be done already. Take a look at the scaffolding output as there may be something wrong with it that is messing up later steps.
