### ISSUE TITLE
Add instructions for how to generate curated fasta file

### ISSUE THREAD

**Issue by mankiddyman** [WarrenLab/hic-scaffolding-nf#4]
I was able to successfully use the pipeliine to output in `out/juicebox_input/out_JBAT.assembly` and `out_JBAT.hic` files and then subsequently make the required changes in Juicebox.

Following the instructions in the [Genome assembly workbook](https://www.dnazoo.org/methods) I exported my assembly from juicebox using _Assembly_ -> _Export Assembly_ to get a new file ending with `...review.assembly`

After that the workbook reccomends using a script from the 3dDNA package but since this workflow doesn't generate merged_nodups.txt  I found an alternative package by the name of [juicebox_scripts](https://github.com/phasegenomics/juicebox_scripts) using the `juicebox_assembly_converter.py` script giving as input the `review.assembly` and `.fasta` files I had used with _hic-scaffolding-nf_ but I get an error saying that the  contigs fail to map.

I am not asking for troubleshooting _juicebox scripts_ but rather how users of this package are generating `.fastas` from their assemblies. 

Help Appreciated!

**Comment by mankiddyman** [comment]
For those curious here is the error messasge from juicebox_scripts 

![image](https://github.com/WarrenLab/hic-scaffolding-nf/assets/81080008/50095402-70fb-46a6-9823-b8abde8b9dfc)

**Comment by esrice** [comment]
Hi Aaryan,

Instructions for just this are in the YAHS documentation:
https://github.com/c-zhou/yahs#manual-curation-with-juicebox-jbat

> Once completed editing, there should be a file named something like `out_JBAT.review.assembly` generated by Juicebox, which can be fed into `juicer post` command to generate AGP and FASTA files for the final genome assembly. You also need the `out_JBAT.liftover.agp` coordinate file previously generated with `juicer pre` command.
> 
>     juicer post -o out_JBAT out_JBAT.review.assembly out_JBAT.liftover.agp contigs.fa
> 
> This will end up with two files `out_JBAT.FINAL.agp` and `out_JBAT.FINAL.fa`. Together with `hic-to-contigs.bin` or the original BED/BAM file, you can regenerate a HiC contact map for the final assembly as described in the previous section.

But this should be in the docs for this pipeline too, so thanks for bringing it to my attention. I'll add that soon.

Ed
