### ISSUE TITLE
issue with reading jucier file

### ISSUE THREAD

**Issue by gargkritika** [WarrenLab/hic-scaffolding-nf#8]
Hi 
I am running hic-scaffolding-nf and the program is unable to read the juicer file. This is the error I am facing

ERROR ~ Error executing process > 'PRINT_VERSIONS'

Caused by:
  Process `PRINT_VERSIONS` terminated with an error exit status (1)

Command executed:

  echo "Chromap: $(chromap --version 2>&1)" > versions.txt
executor >  local (3)
[7c/904a18] PRINT_VERSIONS     | 1 of 1, failed: 1 ✘
[0d/8d4e1e] SAMTOOLS_FAIDX (1) | 0 of 1
[d9/56b04a] CHROMAP_INDEX (1)  | 0 of 1
[-        ] CHROMAP_ALIGN      -
[-        ] YAHS_SCAFFOLD      -
[-        ] JUICER_PRE         -
[-        ] ASSEMBLY_STATS     -
ERROR ~ Error executing process > 'PRINT_VERSIONS'

Caused by:
  Process `PRINT_VERSIONS` terminated with an error exit status (1)

Command executed:

  echo "Chromap: $(chromap --version 2>&1)" > versions.txt
  echo "YAHS: $(yahs --version)" >> versions.txt
  java -jar null -V | grep Version >> versions.txt
  echo "assembly-stats: $(assembly-stats -v)" >> versions.txt

Command exit status:
  1

Command output:
  (empty)

Command error:
  Error: Unable to access jarfile null

Work dir:
  /DATA3/autohic_kritika/hic_scaffolding_tyr/work/7c/904a182d297d8a13665e3dc750dfbb

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

 -- Check '.nextflow.log' file for details

Thank you
Best regards
Kritika

**Comment by esrice** [comment]
Hi Kritika,

Did you download the jar and point the pipeline to its location?

Ed

**Comment by gargkritika** [comment]
Hi Ed

I did do that. However, the issue was that it could not recognize the parameter --juicer-tools-jar. Based on the nextflow.config file I have changed it to --juicerToolsJar and now it is running. Is there some change in the code?

Thank you
Best regards
Kritika

**Comment by esrice** [comment]
Might be a difference in nextflow version where some automatically convert command-line arguments with dashes into camel case and others don't. Better to document the argument that works in both cases, though, so I've fixed that in the README. Thanks for bringing this to my attention!
